import { z } from "astro:content";

export const tagSchema = z.union([
  z.literal("Python"),
  z.literal("Django"),
  z.literal("Pipenv"),
  z.literal("DRF"),
  z.literal("TypeScript"),
  z.literal("セキュリティ"),
  z.literal("React"),
  z.literal("振り返り"),
  z.literal("CSS"),
  z.literal("Vue.js"),
  z.literal("Next.js"),
  z.literal("auth0"),
  z.literal("prettier"),
  z.literal("ESLint"),
  z.literal("styelint"),
  z.literal("VSCode"),
  z.literal("FastAPI"),
  z.literal("読書メモ"),
  z.literal("Jupyter"),
  z.literal("ブログ"),
  z.literal("Gatsby"),
  z.literal("Pylance"),
  z.literal("Docker"),
  z.literal("Node.js"),
  z.literal("npm"),
  z.literal("Heroku"),
  z.literal("PyQt"),
  z.literal("mypy"),
  z.literal("GAS"),
  z.literal("Astro"),
]);

export type Tag = z.infer<typeof tagSchema>;
