name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

env:
  ENV: local

defaults:
  run:
    working-directory: "./"

jobs:
  cache-and-install:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: ./.github/actions/setup_node

      - name: lint
        run: pnpm lint

      - name: generate codes
        run: pnpm --filter=@kimuson.dev/articles generate:summary

      - name: typecheck
        run: pnpm typecheck

      - name: build check
        run: pnpm build
